import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "./components/navbar";
import { UserProvider } from "@/app/components/UserContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Plus Dental Clinic",
  description: "Generated by create Plus Dental Clinic",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <UserProvider>
          {" "}
          <Navbar />
          {children}
        </UserProvider>
      </body>
    </html>
  );
}
